### ISSUE TITLE
spec for self.create_table passes even if method is left empty

### ISSUE THREAD

**Issue by Shmuwol** [learn-co-curriculum/orm-update-lab#11]
It seems that the spec file actually creates the table when spec is run

https://learn.co/tracks/full-stack-web-development/orms-and-activerecord/orms/updating-records-in-an-orm-lab?batch_id=306&question_id=20817&track_id=12615

**Comment by AnnJohn** [comment]
hi @PeterBell this issue needs to be vetted first before someone fixes it.

**Comment by pletcher** [comment]
Fixed in https://github.com/learn-co-curriculum/orm-update-lab/pull/12
