### ISSUE TITLE
missing db folder

### ISSUE THREAD

**Issue by jessenovotny** [learn-co-curriculum/orm-update-lab#16]
The test wouldn't work until I created a db folder and a students.db file

as it stands, `DB = {:conn => SQLite3::Database.new("db/students.db")}` within `config/environment.rb` is looking for a file that doesn't exist. 

Thanks!

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by AnnJohn** [comment]
fixed, thanks!
