### ISSUE TITLE
The instructions for Student.create are incomplete.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/orm-update-lab#20]
I think the instructions for Student.create need to be slightly re-written in the README and in the rspec test.

Currently, the README says this about Student.create: "This method creates a student with two attributes, name and grade." The rspec test says ".create creates a student object with name and grade attributes".

There's just one little problem: in order to pass the test, I have to save the Student object into the database. Neither the README nor the wording in the rspec test said to do this, which is what caused me some confusion. (I should also note that the test doesn't actually check to see that the Student object was created, but that isn't as big of an issue.)

I would simply suggest wording the instructions to say that Student.create creates a student with two attributes, name and grade, _and saves it into the students table_.

Thanks for looking into this!
Sdcrouse

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
